// File: src/SSP.Core/Protocol/Messages.cs
//
// Protocol message definitions shared between the SSP.Server and
// SSP.Client. Messages are exchanged as length-prefixed frames whose
// payload is a JSON document with a "Type" discriminator.
//
// Two distinct message families exist:
//
//   1. Handshake / control messages (this file).
//   2. Tunnel data frames (handled by EncryptedFrame + TunnelCodec).
//
// Every control message is signed or encrypted at the protocol layer
// before being placed on the wire, so the JSON itself is only a
// structural envelope - never trust its fields without verification.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace SSP.Core.Protocol;

/// <summary>Discriminator for control messages on the wire.</summary>
public enum MessageType : int
{
    /// <summary>Server -> Client: ServerNonce + signature.</summary>
    ServerNonce = 1,

    /// <summary>Client -> Server: full enrollment bundle.</summary>
    EnrollmentBundle = 2,

    /// <summary>Server -> Client: enrollment accepted (WAIT) or failure. The Authentication Code is never on the wire.</summary>
    EnrollmentResult = 3,

    /// <summary>Client -> Server: user-entered AuthenticationCode.</summary>
    AuthenticationCode = 4,

    /// <summary>Server -> Client: final authorization outcome ("You verified" / "verification failed").</summary>
    AuthorizationOutcome = 5,

    /// <summary>Server -> Client: challenge nonce for future authorization.</summary>
    ChallengeNonce = 6,

    /// <summary>Client -> Server: signed challenge + fingerprint for future authorization.</summary>
    ChallengeResponse = 7,

    /// <summary>Client -> Server: RSA-OAEP wrapped AES session key.</summary>
    SessionKeyOffer = 8,

    /// <summary>Server -> Client: ack session key.</summary>
    SessionKeyAck = 9,

    /// <summary>Either side: tunnel-level control (e.g. switch to encrypted mode).</summary>
    TunnelControl = 10,
}

public abstract class Message
{
    public abstract MessageType Type { get; }

    public byte[] ToJsonBytes()
    {
        return JsonSerializer.SerializeToUtf8Bytes(this, GetType());
    }

    public static Message? Parse(MessageType type, byte[] payload)
    {
        return type switch
        {
            MessageType.ServerNonce          => JsonSerializer.Deserialize<ServerNonceMessage>(payload),
            MessageType.EnrollmentBundle     => JsonSerializer.Deserialize<EnrollmentBundleMessage>(payload),
            MessageType.EnrollmentResult     => JsonSerializer.Deserialize<EnrollmentResultMessage>(payload),
            MessageType.AuthenticationCode   => JsonSerializer.Deserialize<AuthenticationCodeMessage>(payload),
            MessageType.AuthorizationOutcome => JsonSerializer.Deserialize<AuthorizationOutcomeMessage>(payload),
            MessageType.ChallengeNonce       => JsonSerializer.Deserialize<ChallengeNonceMessage>(payload),
            MessageType.ChallengeResponse    => JsonSerializer.Deserialize<ChallengeResponseMessage>(payload),
            MessageType.SessionKeyOffer      => JsonSerializer.Deserialize<SessionKeyOfferMessage>(payload),
            MessageType.SessionKeyAck        => JsonSerializer.Deserialize<SessionKeyAckMessage>(payload),
            MessageType.TunnelControl        => JsonSerializer.Deserialize<TunnelControlMessage>(payload),
            _ => throw new InvalidDataException($"Unknown message type {type}.")
        };
    }
}

// ────────────────────────────────────────────────────────────────────
// Message bodies
// ────────────────────────────────────────────────────────────────────

public sealed class ServerNonceMessage : Message
{
    public override MessageType Type => MessageType.ServerNonce;

    /// <summary>Base64-encoded random nonce generated by the server.</summary>
    public string ServerNonceB64 { get; set; } = string.Empty;

    /// <summary>Base64-encoded RSA signature over ServerNonce.</summary>
    public string ServerNonceSignatureB64 { get; set; } = string.Empty;
}

public sealed class EnrollmentBundleMessage : Message
{
    public override MessageType Type => MessageType.EnrollmentBundle;

    public string ClientPublicKeyPem { get; set; } = string.Empty;
    public string ClientNonceB64 { get; set; } = string.Empty;
    public string ClientNonceSignatureB64 { get; set; } = string.Empty;
    public string OneTimeToken { get; set; } = string.Empty;
}

public sealed class EnrollmentResultMessage : Message
{
    public override MessageType Type => MessageType.EnrollmentResult;

    /// <summary>True if the OneTimeToken + signature validated successfully.</summary>
    public bool Success { get; set; }

    /// <summary>
    /// When <see cref="Success"/> is true this MUST be empty (the
    /// Authentication Code is displayed on the SERVER console only,
    /// never transmitted to the client). When false, contains an
    /// error description. See spec §13 / §15.
    /// </summary>
    public string ErrorOrWait { get; set; } = string.Empty;
}

public sealed class AuthenticationCodeMessage : Message
{
    public override MessageType Type => MessageType.AuthenticationCode;

    public string Code { get; set; } = string.Empty;
}

public sealed class AuthorizationOutcomeMessage : Message
{
    public override MessageType Type => MessageType.AuthorizationOutcome;

    public bool Authorized { get; set; }

    public string Message { get; set; } = string.Empty;
}

public sealed class ChallengeNonceMessage : Message
{
    public override MessageType Type => MessageType.ChallengeNonce;

    /// <summary>Base64-encoded server-signed nonce (future authorization).</summary>
    public string ChallengeNonceB64 { get; set; } = string.Empty;

    /// <summary>Base64-encoded RSA signature over ChallengeNonce.</summary>
    public string ChallengeNonceSignatureB64 { get; set; } = string.Empty;
}

public sealed class ChallengeResponseMessage : Message
{
    public override MessageType Type => MessageType.ChallengeResponse;

    public string ClientPublicKeyFingerprint { get; set; } = string.Empty;
    public string SignedChallengeB64 { get; set; } = string.Empty;
}

public sealed class SessionKeyOfferMessage : Message
{
    public override MessageType Type => MessageType.SessionKeyOffer;

    /// <summary>
    /// Base64-encoded RSA-OAEP ciphertext of the AES-256 session key.
    /// </summary>
    public string WrappedSessionKeyB64 { get; set; } = string.Empty;
}

public sealed class SessionKeyAckMessage : Message
{
    public override MessageType Type => MessageType.SessionKeyAck;

    public bool Accepted { get; set; }
}

public sealed class TunnelControlMessage : Message
{
    public override MessageType Type => MessageType.TunnelControl;

    /// <summary>"BeginEncrypted" / "End" / etc.</summary>
    public string Command { get; set; } = string.Empty;
}

// ────────────────────────────────────────────────────────────────────
// Wire envelope: every control message is sent as
//   [4-byte length][1-byte type discriminator][JSON body]
// so the receiver can deserialize without a switch up-front.
// ────────────────────────────────────────────────────────────────────

public static class MessageWire
{
    /// <summary>Serialize a control message to a frame payload.</summary>
    public static byte[] ToPayload(Message message)
    {
        var json = message.ToJsonBytes();
        var payload = new byte[1 + json.Length];
        payload[0] = (byte)message.Type;
        Buffer.BlockCopy(json, 0, payload, 1, json.Length);
        return payload;
    }

    /// <summary>
    /// Read a single control message from a stream. Returns null at a
    /// clean frame boundary.
    /// </summary>
    public static async Task<Message?> ReadAsync(Stream stream, CancellationToken ct = default)
    {
        var payload = await Frame.ReadAsync(stream, ct).ConfigureAwait(false);
        if (payload == null) return null;
        if (payload.Length < 1)
            throw new InvalidDataException("Control frame too short to contain a type byte.");

        var type = (MessageType)payload[0];
        var body = new byte[payload.Length - 1];
        Buffer.BlockCopy(payload, 1, body, 0, body.Length);
        return Message.Parse(type, body);
    }

    /// <summary>Write a single control message to a stream.</summary>
    public static async Task WriteAsync(Stream stream, Message message, CancellationToken ct = default)
    {
        var payload = ToPayload(message);
        await Frame.WriteAsync(stream, payload, ct).ConfigureAwait(false);
    }
}
