// File: src/SSP.Core/Crypto/TokenGenerator.cs
//
// Generators for the two human / machine consumable secrets used by the
// enrollment protocol:
//
//   * OneTimeToken  - a 256-bit cryptographically secure random value,
//                     base64url encoded. Created during SETUP, embedded
//                     into the client at patch time, and presented to
//                     the server during the first enrollment. The server
//                     stores only its SHA-256 hash and deletes that hash
//                     after a successful enrollment. It is NOT the
//                     Authentication Code and is never typed by a human.
//
//   * AuthenticationCode - a 10-digit numeric code generated by the
//                          SERVER during enrollment, AFTER the One-Time
//                          Token has already validated. It is displayed
//                          on the server machine (never transmitted to
//                          the client). The administrator reads it to
//                          the client operator, who types it into the
//                          client. Single-use.

using System.Security.Cryptography;
using System.Text;

namespace SSP.Core.Crypto;

public static class TokenGenerator
{
    /// <summary>
    /// Length of the One-Time Token in raw bytes (256 bits).
    /// </summary>
    public const int OneTimeTokenSizeBytes = 32;

    /// <summary>
    /// Length of the Authentication Code in decimal digits.
    /// </summary>
    public const int AuthenticationCodeDigits = 10;

    /// <summary>
    /// Generate a new One-Time Token as a base64url string (no padding).
    /// </summary>
    public static string GenerateOneTimeToken()
    {
        var bytes = RandomNumberGenerator.GetBytes(OneTimeTokenSizeBytes);
        return Base64UrlEncode(bytes);
    }

    /// <summary>
    /// Compute the SHA-256 hash of a One-Time Token, returned as a
    /// lowercase hex string. This is the value stored on the server.
    /// </summary>
    public static string HashOneTimeToken(string oneTimeToken)
    {
        var bytes = Encoding.UTF8.GetBytes(oneTimeToken);
        var hash = SHA256.HashData(bytes);
        return Convert.ToHexString(hash).ToLowerInvariant();
    }

    /// <summary>
    /// Constant-time comparison of two hex/hash strings. Used to verify
    /// a presented One-Time Token against the stored hash without leaking
    /// timing information.
    /// </summary>
    public static bool ConstantTimeEquals(string a, string b)
    {
        if (a.Length != b.Length) return false;
        var result = 0;
        for (var i = 0; i < a.Length; i++)
            result |= a[i] ^ b[i];
        return result == 0;
    }

    /// <summary>
    /// Generate a cryptographically secure 10-digit authentication code.
    /// The first digit is guaranteed to be non-zero so the value always
    /// has exactly 10 digits when formatted as a string.
    /// </summary>
    public static string GenerateAuthenticationCode()
    {
        var bytes = RandomNumberGenerator.GetBytes(AuthenticationCodeDigits);
        var sb = new StringBuilder(AuthenticationCodeDigits);
        for (var i = 0; i < AuthenticationCodeDigits; i++)
        {
            var digit = bytes[i] % 10;
            if (i == 0 && digit == 0)
                digit = 1; // ensure the first digit is non-zero
            sb.Append((char)('0' + digit));
        }
        return sb.ToString();
    }

    /// <summary>
    /// Generate a cryptographically secure random nonce of the requested
    /// length. Used for ServerNonce / ClientNonce / ChallengeNonce which
    /// are 32 bytes each.
    /// </summary>
    public static byte[] GenerateNonce(int bytes = 32)
    {
        return RandomNumberGenerator.GetBytes(bytes);
    }

    /// <summary>Base64url encoder without padding.</summary>
    public static string Base64UrlEncode(byte[] bytes)
    {
        var s = Convert.ToBase64String(bytes);
        s = s.Replace('+', '-').Replace('/', '_');
        var end = s.IndexOf('=');
        if (end >= 0) s = s.Substring(0, end);
        return s;
    }

    /// <summary>Base64url decoder that accepts both padded and unpadded input.</summary>
    public static byte[] Base64UrlDecode(string s)
    {
        var padded = s.Replace('-', '+').Replace('_', '/');
        switch (padded.Length % 4)
        {
            case 2: padded += "=="; break;
            case 3: padded += "="; break;
            case 0: break;
            default: throw new FormatException("Invalid base64url length.");
        }
        return Convert.FromBase64String(padded);
    }
}
