// File: src/SSP.Server/UI/AuthenticationCodeDialog.cs
//
// Native Windows presentation of the enrollment Authentication Code.
//
// The SSP.Server normally runs as a Windows Service under LocalSystem in
// Session 0, which has no interactive console. A plain Console.WriteLine
// is therefore invisible to the administrator sitting at the interactive
// desktop. Writing the code to a text file was an unacceptable workaround.
//
// MessageBoxW + MB_SERVICE_NOTIFICATION is the historical Session-0 trick,
// but on modern Windows (NoInteractiveServices = 1 by default) that call
// is suppressed or lands on the isolated Session 0 desktop. Administrators
// who are logged on at the console or over RDP never see it.
//
// The production path is therefore WTSSendMessageW targeted at every
// WTSActive interactive session. That API is specifically for a service
// to put a message box on a user's desktop without a helper process.
// MessageBoxW + MB_SERVICE_NOTIFICATION is retained only as a last-resort
// fallback (e.g. --run-once with no enumerable session).
//
// On non-Windows hosts (and when the SSP_SUPPRESS_AUTH_DIALOG environment
// variable is set, e.g. during automated tests) ShowAsync returns without
// displaying anything; the caller is responsible for a console/logger
// fallback. FormatForDisplay is a pure function so it can be unit tested
// without any UI.

using System.Runtime.InteropServices;
using System.Runtime.Versioning;

namespace SSP.Server.UI;

/// <summary>
/// Shows the server-generated Authentication Code to the local
/// administrator via a native Windows dialog.
/// </summary>
public static class AuthenticationCodeDialog
{
    /// <summary>Dialog title (constant, per spec §7).</summary>
    public const string Title = "SSP Authentication";

    // MessageBox / WTSSendMessage flags (winuser.h).
    private const uint MB_OK                   = 0x00000000;
    private const uint MB_ICONINFORMATION      = 0x00000040;
    private const uint MB_TOPMOST              = 0x00040000;
    private const uint MB_SERVICE_NOTIFICATION = 0x00200000;
    private const uint MB_SETFOREGROUND        = 0x00010000;

    private const uint WTSActive = 0;

    /// <summary>
    /// Environment variable that, when set, suppresses the native dialog.
    /// Used by automated test runs so a service-notification message box
    /// never blocks a headless CI agent.
    /// </summary>
    public const string SuppressEnvironmentVariable = "SSP_SUPPRESS_AUTH_DIALOG";

    /// <summary>
    /// Group a 10-digit code for human-friendly display as "AAA BBB CCCC",
    /// e.g. "5831940271" -> "583 194 0271". Presentation only: the
    /// returned string must never be used for validation, hashing, or
    /// comparison - those continue to use the raw 10-digit value.
    /// Codes that are not exactly 10 ASCII digits are returned unchanged.
    /// </summary>
    public static string FormatForDisplay(string code)
    {
        if (string.IsNullOrEmpty(code) || code.Length != 10)
            return code;
        for (var i = 0; i < code.Length; i++)
        {
            if (code[i] < '0' || code[i] > '9')
                return code;
        }
        return code.Substring(0, 3) + " " + code.Substring(3, 3) + " " + code.Substring(6, 4);
    }

    /// <summary>
    /// Display a native dialog showing the application name and the
    /// Authentication Code on every active interactive user's desktop.
    ///
    /// On non-Windows or when suppressed, this is a no-op so the caller's
    /// console fallback remains the presentation channel (used by Linux
    /// integration tests and headless CI).
    /// </summary>
    /// <param name="applicationName">
    /// Dynamic protected-application name (RDP, WEB, SSH, ...).
    /// </param>
    /// <param name="authenticationCode">
    /// The raw 10-digit code generated by the server. It is formatted for
    /// display only; the underlying value is not altered.
    /// </param>
    public static Task ShowAsync(string applicationName, string authenticationCode)
    {
        if (!OperatingSystem.IsWindows())
            return Task.CompletedTask;

        if (!string.IsNullOrEmpty(Environment.GetEnvironmentVariable(SuppressEnvironmentVariable)))
            return Task.CompletedTask;

        return ShowWindowsAsync(applicationName, authenticationCode);
    }

    [SupportedOSPlatform("windows")]
    private static Task ShowWindowsAsync(string applicationName, string authenticationCode)
    {
        var displayCode = FormatForDisplay(authenticationCode);
        var app = string.IsNullOrWhiteSpace(applicationName) ? "SSP" : applicationName;

        var text =
            "\r\n" +
            $"        {app}\r\n" +
            "\r\n" +
            "    Authentication Code\r\n" +
            "\r\n" +
            $"        {displayCode}\r\n" +
            "\r\n" +
            "    Enter this code on the client.\r\n";

        // WTSSendMessage / MessageBox are blocking native calls; offload
        // them so enrollment is not stuck on a thread-pool thread. The
        // protocol does not await this Task.
        return Task.Run(() => PresentOnInteractiveDesktops(text));
    }

    [SupportedOSPlatform("windows")]
    private static void PresentOnInteractiveDesktops(string text)
    {
        var style = MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND;
        var presented = false;
        var sessions = EnumerateInteractiveSessionIds();

        if (sessions.Count == 0)
        {
            // Case C: no console and no RDP user is logged on. Do not
            // report the code as shown — Session 0 has no administrator
            // desktop. The console banner remains the only channel.
            Console.Error.WriteLine(
                "[authentication-dialog] No interactive Windows session (console or RDP) is logged on. " +
                "The Authentication Code cannot be shown on a desktop.");
        }

        foreach (var sessionId in sessions)
        {
            try
            {
                // Lengths are in BYTES (Unicode). Do not use
                // MB_SERVICE_NOTIFICATION here: WTSSendMessage already
                // targets a specific user session.
                var ok = WTSSendMessageW(
                    IntPtr.Zero,
                    sessionId,
                    Title,
                    (uint)(Title.Length * 2),
                    text,
                    (uint)(text.Length * 2),
                    style,
                    0,
                    out _,
                    false);
                if (ok)
                {
                    presented = true;
                }
                else
                {
                    Console.Error.WriteLine(
                        $"[authentication-dialog] WTSSendMessage to session {sessionId} failed (win32={Marshal.GetLastWin32Error()}).");
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine(
                    $"[authentication-dialog] WTSSendMessage session {sessionId}: {ex.Message}");
            }
        }

        if (presented)
            return;

        // Last resort for an interactive --run-once process whose
        // sessions we failed to enumerate. On a Session 0 service with
        // no logged-on user this is usually blocked by
        // NoInteractiveServices and must not be treated as success.
        var box = MessageBoxW(
            IntPtr.Zero,
            text,
            Title,
            style | MB_SERVICE_NOTIFICATION);
        if (box == 0)
        {
            Console.Error.WriteLine(
                $"[authentication-dialog] MessageBoxW failed (win32={Marshal.GetLastWin32Error()}). " +
                "The Authentication Code was printed on the server console; it is not visible from a Windows Service.");
        }
        else if (sessions.Count == 0)
        {
            Console.Error.WriteLine(
                "[authentication-dialog] MessageBoxW returned success but no interactive session was enumerated. " +
                "Do not assume an administrator saw the Authentication Code.");
        }
    }

    /// <summary>
    /// Active interactive sessions (not Session 0). Falls back to the
    /// physical console session when no WTSActive session is listed —
    /// typical when the only logon is the console itself.
    /// </summary>
    [SupportedOSPlatform("windows")]
    private static List<uint> EnumerateInteractiveSessionIds()
    {
        var active = new List<uint>();

        if (WTSEnumerateSessionsW(IntPtr.Zero, 0, 1, out var ptr, out var count)
            && ptr != IntPtr.Zero)
        {
            try
            {
                var size = Marshal.SizeOf<WTS_SESSION_INFO>();
                for (var i = 0; i < count; i++)
                {
                    var info = Marshal.PtrToStructure<WTS_SESSION_INFO>(IntPtr.Add(ptr, i * size));
                    // WTSActive covers a physical console login and an
                    // RDP login that is currently attached. Session 0
                    // is the service session and is never a desktop.
                    if (info.SessionId != 0 && info.State == WTSActive)
                        active.Add(info.SessionId);
                }
            }
            finally
            {
                WTSFreeMemory(ptr);
            }
        }
        else
        {
            Console.Error.WriteLine(
                $"[authentication-dialog] WTSEnumerateSessions failed (win32={Marshal.GetLastWin32Error()}).");
        }

        if (active.Count > 0)
            return active;

        var console = WTSGetActiveConsoleSessionId();
        if (console != 0 && console != 0xFFFFFFFFu)
            active.Add(console);

        return active;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct WTS_SESSION_INFO
    {
        public uint SessionId;
        public IntPtr pWinStationName;
        public uint State;
    }

    [SupportedOSPlatform("windows")]
    [DllImport("wtsapi32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    private static extern bool WTSSendMessageW(
        IntPtr hServer,
        uint SessionId,
        string pTitle,
        uint TitleLength,
        string pMessage,
        uint MessageLength,
        uint Style,
        uint Timeout,
        out uint pResponse,
        bool bWait);

    [SupportedOSPlatform("windows")]
    [DllImport("wtsapi32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    private static extern bool WTSEnumerateSessionsW(
        IntPtr hServer,
        uint Reserved,
        uint Version,
        out IntPtr ppSessionInfo,
        out uint pCount);

    [SupportedOSPlatform("windows")]
    [DllImport("wtsapi32.dll")]
    private static extern void WTSFreeMemory(IntPtr memory);

    [SupportedOSPlatform("windows")]
    [DllImport("kernel32.dll")]
    private static extern uint WTSGetActiveConsoleSessionId();

    [SupportedOSPlatform("windows")]
    [DllImport("user32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    private static extern int MessageBoxW(IntPtr hWnd, string text, string caption, uint type);
}
